### ISSUE TITLE
Intel-vaapi-driver fails to compile on GCC 7.1.1

### ISSUE THREAD

**Issue by stripes416** [01org/intel-vaapi-driver#236]
```
22:29:24,966 INFO  - i965_test_fixture.cpp: In member function 'Surfaces I965TestFixture::createSurfaces(int, int, int, size_t, const SurfaceAttribs&)':
22:29:24,966 INFO  - i965_test_fixture.cpp:47:12: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=dangling-else]
22:29:24,966 INFO  - if (ctx)
22:29:24,966 INFO  - ^
22:29:24,976 INFO  - i965_test_environment.cpp: In member function 'virtual void I965TestEnvironment::TearDown()':
22:29:24,976 INFO  - i965_test_environment.cpp:85:8: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=dangling-else]
22:29:24,976 INFO  - if (m_vaDisplay)
22:29:24,976 INFO  - ^
22:29:25,073 INFO  - i965_config_test.cpp: In member function 'virtual void I965ConfigTest_Create_Test::TestBody()':
22:29:25,073 INFO  - i965_config_test.cpp:61:8: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=dangling-else]
22:29:25,073 INFO  - if (actual != VA_STATUS_SUCCESS)
22:29:25,073 INFO  - ^
```

**Comment by uartie** [comment]
https://github.com/google/googletest/issues/1119
